### PR TITLE
Added reset method to data collector for symfony4 compatibilty

### PR DESCRIPTION
**Pull request by ilukac**
Added reset() method to Contentful data collector for Symfony 4 compatibility

### CODE REVIEW

**Comment by dborsatto** [comment]
Hey @ilukac,

first of all, thanks for your contribution! In order to be compatible with Symfony 4, I'll have to also update the values in `composer.json` (and possibly think about which versions we want to support). I'll have to check the docs, to be sure I understand what your PR is doing (it seems very simple, but I need to verify that).

Until the SF4 isn't released yet I'm not considering this the most urgent priority, but rest assured I'll work on this as soon as I have some time 🙂

**Comment by ilukac** [comment]
Hi Davide,

Sorry, I forgot to note that this is not really urgent. I just came across a deprecation warning when trying out symfony 3.4beta1 and gave it a few minutes for a fix.

Its for the bright future :)

Cheers

**Comment by cjost1988** [comment]
Hello @dborsatto.

Since symfony 4 is released, could you give a short estimation when you'll add the support for it or at least merge this PR?

Cheers.

**Comment by dborsatto** [comment]
Hey all,

at the moment I'm working on a different project (which is also based on Symfony, but doesn't use this bundle). I will tackle Symfony 4 compatibility either next week or (more likely) in January after the Christmas break 🙂

**Comment by cjost1988** [comment]
Thank you @dborsatto for the quick response.
I've already created a branch with the `reset()` fix, as well as tests for it. There were some more little issues which I already fixed.

If I've the time, I'll submit the PR until the end of the week and you can use it as base. Just to spare some time :)

**Pull request merged**
