### PR TITLE
Fix testing fixture.  Change the ordering.

### PR DESCRIPTION
**Pull request by mariobodemann**
The line ordering was causing unit test to fail.

### CODE REVIEW

**Comment by mariobodemann** [comment]
@yadakhov Once you got a minute, can you check what this failure means:

```
Loaded config default from "/home/mario/Contentful/ContentfulBundle/.php_cs".
F
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
   1) scripts/create-redirector.php (header_comment)

Checked all files in 0.022 seconds, 10.000 MB memory used
Script $([ -f php-cs-fixer.phar ] && echo "php php-cs-fixer.phar" || echo "php-cs-fixer") fix --dry-run --stop-on-violation -v handling the lint-syntax event returned with error code 
```
https://circleci.com/gh/contentful/ContentfulBundle/44

**Comment by yadakhov** [comment]
> @yadakhov Once you got a minute, can you check what this failure means:
> 
> ```
> Loaded config default from "/home/mario/Contentful/ContentfulBundle/.php_cs".
> F
> Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
>    1) scripts/create-redirector.php (header_comment)
> 
> Checked all files in 0.022 seconds, 10.000 MB memory used
> Script $([ -f php-cs-fixer.phar ] && echo "php php-cs-fixer.phar" || echo "php-cs-fixer") fix --dry-run --stop-on-violation -v handling the lint-syntax event returned with error code 
> ```
> https://circleci.com/gh/contentful/ContentfulBundle/44

I will run the php linter.  I believe we need to do a chore to update the copyright notice.

**Comment by yadakhov** [comment]
github not updating this PR branch with my new commits.  I'm going to close this PR and create a new one with all the changes.

**Comment by yadakhov** [comment]
This PR can be closed.  I created a new PR https://github.com/contentful/ContentfulBundle/pull/39

**Pull request closed without merging**
