### PR TITLE
Symfony4 compatibility

### PR DESCRIPTION
**Pull request by jansabat**

### CODE REVIEW

**Comment by dborsatto** [comment]
Hey @jansabat,
thanks for the contribution!

First of all, testing is currently done by using a `.phar` version of PHPUnit, so please don't add it to the dependencies.

Secondly, adding `ChildDefinition` instead of `DefinitionDecorator` indeed makes the bundle compatible with Symfony 4, but also makes it incompatible with Symfony < 3.3 (despite what is stated in `composer.json`).

Given the incompatibilities of the two versions, I'd have to maintain two branches, which is different than what we've been doing until now. I'll have to discuss this internally and see how to best approach this, but I'll make sure to keep you updated.

**Comment by kobelobster** [comment]
@dborsatto Any news on this?

**Comment by dborsatto** [comment]
Hey,

here's a status update: I've recently released a beta version of v3 of the Delivery SDK, and I will soon release another beta of the Management SDK. They both include quite big internal changes, so I was postponing working on both Symfony and Laravel integrations until I can release both SDKs as stable, so I can base the integrations on the new versions rather than releasing a new major version for Symfony 4 support, and then immediately having to release another major version because the SDK includes breaking changes.

The only slight problem is that the timeline does not entirely depend on me. The SDKs now require a functionality called space environments, which is currently in beta and available to a limited group of users, so that'll have to be available for everyone before I can release a new stable version. Currently we're targeting somewhere around half of April, so hopefully the Symfony Bundle will come by the end of the month ☺️

Cheers,

Davide

**Comment by kobelobster** [comment]
Makes sense, however, we're going to upgrade our application to Symfony 4 soon. I see two options

a.) We fork the project and just use our own repo until a stable version is released
b.) This PR gets merged and you would create pre-release (which can contain BC breaks)

I'm going out on a limb now and say that b probably won't happen and that you'll release a new version only when SDK v3 is integrated, right? So that would leave us with a, meaning we fork.

Edit: Regarding the Symfony version problem: That could be done via `class_exists` or by using `Kernel::VERSION`

**Comment by dborsatto** [comment]
So, I'm not necessarily against option B, but the problem with that would be that I'd have to create a v3-beta of this bundle, which would be dependent of v2 of the SDK, which goes a bit against our current plans in terms of versions.

I'm sorry I can't be of more help, this time I just need to work around others' needs 😞

**Comment by dborsatto** [comment]
Replaced by #25

**Pull request closed without merging**
